name: Test Code Examples

on:
  schedule:
    # Run at 9am UTC daily
    - cron: '0 9 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Check code examples in docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install --no-interaction --all-extras

    - name: Run tests
      run: poetry run pytest
      env:
        PORTIA_API_KEY: ${{ secrets.PORTIA_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}


    - name: Notify Slack on failure
      if: failure() && github.ref == 'refs/heads/main'
      uses: slackapi/slack-github-action@v1.27.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        slack-message: "Docs testing failed! See https://github.com/portiaAI/docs/actions/runs/${{ github.run_id }} for more details."
        channel-id: C07V8NK09RC