name: Test Code Examples

on:
  schedule:
    # Run at 9am UTC daily
    - cron: '0 9 * * *'
  workflow_dispatch:
  push:

jobs:
  test:
    name: Check code examples in docs
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-examples
        # Install any other dependencies your tests need
        pip install -e .

    - name: Run tests
      run: pytest -s tests/test_code_examples.py
      env:
        PORTIA_API_KEY: ${{ secrets.PORTIA_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }} 